dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"


detail_urls = [
    path("project/<slug:project_id>/", views.DetailProjectView.as_view(), name="detail_project"),
    path("topic/<slug:topic_id>/", views.DetailTopicView.as_view(), name="detail_topic"),
    path("dataobject/<slug:dataobject_id>", views.DetailDataObjectView.as_view(), name="detail_dataobject"),
]

new_urls = [
    path("project/new/", views.NewProjectView.as_view(), name="new_project"),
    path("topic/new/<slug:project_id>/", views.NewTopicView.as_view(), name="new_topic"),
    path("dataobject/new/<slug:topic_id>", views.NewDataObject.as_view(), name="new_dataobject"),
]

delete_urls = [
    path("project/delete/<slug:project_id>/", views.DeleteProjectView.as_view(), name="delete_project"),
    path("topic/delete/<slug:topic_id>/", views.DeleteTopicView.as_view(), name="delete_topic"),
    path("dataobject/delete/<slug:dataobject_id>", views.DeleteDataObject.as_view(), name="delete_dataobject")
]

edit_urls = [
    path("dataobject/edit/<slug:dataobject_id>", views.EditDataObjectView.as_view(), name="edit_dataobject"),
]

ajax_urls = [
    path("htmx_ajax/topic/mongo_dataobject/<slug:topic_id>", views.QueryDataObjectsView.as_view(),
         name="query_dataobjects"),
    path("htmx_ajax/mongo_dataobject/values/<slug:dataobject_id>/", views.QueryDataObjectValues.as_view(),
         name="get_dataobject_values"),
    path("html_ajax/connection/refresh", views.RefreshConnectionsView.as_view(), name="refresh_connections"),
    path("html_ajax/connection/check/<slug:project_id>", views.CheckConnectionView.as_view(), name="check_connection"),
]

download_urls = [
    path("download/dataobject/<slug:dataobject_id>/", views.DownloadView.as_view(), name="download_csv"),
]

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
] + new_urls + delete_urls + detail_urls + ajax_urls + download_urls + edit_urls

ist_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('auth/', include("authentication.urls")),
    path('', include("dashboard.urls")),
]

templates/dashboard/detail/include/project_content.html
{% load static %}
{% for topic in topics %}
<div id="div-topic-{{ topic.id }}">
    <div class="uk-card uk-card-default uk-card-hover uk-card-small">
        <div class="uk-position-top-right uk-flex-row uk-padding-small">
            {% with button1_icon="more" button2_icon="trash" target_prefix="div-topic-" target_id=topic.id %}
            {% url 'dashboard:detail_topic' topic.id as button1_url %}
            {% url 'dashboard:delete_topic' topic.id as button2_url %}
            {% include "../../partials/card_btns.html" %}
            {% endwith %}
        </div>
        <div class="uk-card-header">
            <div>
                <h3>
                    {{ topic.name }}
                    <span class="uk-h6">({{ topic.path }})</span>
                </h3>
            </div>
        </div>
        <div class="uk-card-body">
            <div class="uk-container uk-container-expand uk-container-large" id="div_topic{{ topic.id }}" hx-get="{% url 'dashboard:query_dataobjects' topic.id %}" hx-trigger="load" hx-swap="outerHTML">
                <div class="uk-grid">
                    <div>
                        <img id="new-indicator" class="htmx-indicator" src="{% static 'svg-loaders/tail-spin.svg' %}">
                        <span class="uk-container">Fetching Data...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<h5 class="uk-h5">No topics...</h5>
{% endfor %}

templates/dashboard/detail/include/topic_content.html
{% load static %}
{% for obj in data_objects %}
<div id="div-dataobj-{{ obj.id }}">
    <div class="uk-card uk-card-default uk-card-hover">
        <img id="reload-indicator" class="htmx-indicator" src="{% static 'svg-loaders/tail-spin.svg' %}" width="28">
        <div class="uk-position-top-right uk-flex-row uk-padding-small">
            <!-- <button class="uk-button uk-button-default uk-button-small" type="button"> -->
            <a href="{% url 'dashboard:detail_dataobject' obj.id %}" class="uk-text-secondary uk-button uk-button-small uk-button-default">
                <span uk-icon="file-text"></span>
            </a>
            <button hx-get="{% url 'dashboard:edit_dataobject' obj.id %}" hx-target="#edit-dataobject-dialog" class="uk-text-secondary uk-button uk-button-small uk-button-default">
                <span uk-icon="pencil"></span>
            </button>
            <!-- </button> -->
            {% with button2_icon="trash" target_prefix="div-dataobj-" target_id=obj.id %}
            {% url 'dashboard:delete_dataobject' obj.id as button2_url %}
            {% include "../../partials/card_btns.html" %}
            {% endwith %}
        </div>
        <div class="uk-card-header">
            <div>
                <h3>
                    {{ obj.name }}
                    <span class="uk-h6">
                        {% if obj.path %}
                        ({{ obj.path }})
                        {% else %}
                        ({{ obj.key }})
                        {% endif %}
                    </span>
                </h3>
            </div>
        </div>
        <div class="uk-card-body">
            <div class="uk-margin">
                <div class="uk-container uk-container-expand uk-container-small" id="div-dataobj-{{ obj.id }}" hx-get="{% url 'dashboard:get_dataobject_values' obj.id %}" hx-trigger="load" hx-swap="outerHTML">
                    <div class="uk-container uk-container-expand">
                        <img src="{% static 'svg-loaders/tail-spin.svg' %}" width="50"> <span class="uk-container uk-container-expand">Fetching data...</span>
                    </div>
                </div>
                <div class="uk-container uk-container-expand" id="div-values-{{ obj.id }}">
                </div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<h5 class="uk-h5">No Data Fields...</h5>
{% endfor %}