dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"


detail_urls = [
    path("project/<slug:project_id>/", views.DetailProjectView.as_view(), name="detail_project"),
    path("topic/<slug:topic_id>/", views.DetailTopicView.as_view(), name="detail_topic"),
    path("dataobject/<slug:dataobject_id>", views.DetailDataObjectView.as_view(), name="detail_dataobject"),
]

new_urls = [
    path("project/new/", views.NewProjectView.as_view(), name="new_project"),
    path("topic/new/<slug:project_id>/", views.NewTopicView.as_view(), name="new_topic"),
    path("dataobject/new/<slug:topic_id>", views.NewDataObject.as_view(), name="new_dataobject"),
]

delete_urls = [
    path("project/delete/<slug:project_id>/", views.DeleteProjectView.as_view(), name="delete_project"),
    path("topic/delete/<slug:topic_id>/", views.DeleteTopicView.as_view(), name="delete_topic"),
    path("dataobject/delete/<slug:dataobject_id>", views.DeleteDataObject.as_view(), name="delete_dataobject")
]

edit_urls = [
    path("dataobject/edit/<slug:dataobject_id>", views.EditDataObjectView.as_view(), name="edit_dataobject"),
]

ajax_urls = [
    path("htmx_ajax/topic/mongo_dataobject/<slug:topic_id>", views.QueryDataObjectsView.as_view(),
         name="query_dataobjects"),
    path("htmx_ajax/mongo_dataobject/values/<slug:dataobject_id>/", views.QueryDataObjectValues.as_view(),
         name="get_dataobject_values"),
    path("html_ajax/connection/refresh", views.RefreshConnectionsView.as_view(), name="refresh_connections"),
    path("html_ajax/connection/check/<slug:project_id>", views.CheckConnectionView.as_view(), name="check_connection"),
]

download_urls = [
    path("download/dataobject/<slug:dataobject_id>/", views.DownloadView.as_view(), name="download_csv"),
]

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
] + new_urls + delete_urls + detail_urls + ajax_urls + download_urls + edit_urls

ist_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('auth/', include("authentication.urls")),
    path('', include("dashboard.urls")),
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse


class BaseModel(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(max_length=256)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Project(BaseModel):
    host = models.CharField(max_length=64)
    port = models.IntegerField()
    username = models.CharField(max_length=32, null=True, blank=True)
    password = models.CharField(max_length=32, null=True, blank=True)
    connected = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.datetime.now())
    db_name = models.CharField(max_length=64)

    class Meta:
        permissions = (
            ("is_owner", "Has all permissions"),
            ("can_add", "Can create new project"),
            ("can_delete", "Can delete project"),
            ("can_view", "View only permission"),
        )


class Topic(BaseModel):
    QOS_CHOICES = [
        (0, "0 (At Most Once)"),
        (1, "1 (At Least Once)"),
        (2, "2 (Exactly Once)")
    ]

    path = models.CharField(max_length=64, default="/")
    sub = models.BooleanField(default=True)
    pub = models.BooleanField(default=False)
    qos = models.IntegerField(default=0, choices=QOS_CHOICES)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class DataObject(BaseModel):
    FORMAT_CHOICE_JSON = "JSON"
    FORMAT_CHOICE_SINGLE_VARIABLE = "SINGL"
    FORMAT_CHOICES = [
        (FORMAT_CHOICE_JSON, "JSON"),
        (FORMAT_CHOICE_SINGLE_VARIABLE, "Single Variable"),
    ]

    DATA_TYPE_NUMBER = "NUM"
    DATA_TYPE_STRING = "STR"
    DATA_TYPE_LOCATION = "LOC"
    DATA_TYPE_BOOLEAN = "BOOL"
    DATA_TYPE_CHOICES = [
        (DATA_TYPE_NUMBER, "Number"),
        (DATA_TYPE_STRING, "String"),
        (DATA_TYPE_LOCATION, "Location(Disabled)"),
        (DATA_TYPE_BOOLEAN, "Boolean"),
    ]

    WIDGET_TYPE_SCATTER = "SCATTER"
    WIDGET_TYPE_LINE = "LINE"
    WIDGET_TYPE_STATUS = "STATUS"
    WIDGET_TYPE_MAP = "MAP"
    WIDGET_TYPE_CHOICES = [
        (WIDGET_TYPE_SCATTER, "Scatter Plot"),
        (WIDGET_TYPE_LINE, "Line plot"),
        (WIDGET_TYPE_STATUS, "Status Indicator(Disabled)"),
        (WIDGET_TYPE_MAP, "Map(Disabled)")
    ]

    format = models.CharField(max_length=5, choices=FORMAT_CHOICES)
    data_type = models.CharField(max_length=5, choices=DATA_TYPE_CHOICES)
    widget_type = models.CharField(max_length=10, choices=WIDGET_TYPE_CHOICES, default=WIDGET_TYPE_LINE)
    path = models.CharField(max_length=64, null=True, blank=True)
    key = models.CharField(max_length=32, null=True, blank=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

dashboard/forms.py
from django import forms

from .models import Topic, DataObject


class NewProjectForm(forms.Form):
    name = forms.CharField(label="name", max_length=32)
    desc = forms.CharField(label="desc", max_length=256, required=False)
    mqtt_host = forms.CharField(label="mqtt_host", max_length=32)
    mqtt_port = forms.IntegerField(label="mqtt_port")
    mqtt_username = forms.CharField(label="username", max_length=32, required=False)
    mqtt_password = forms.CharField(label="password", max_length=32, required=False)


class NewTopicForm(forms.Form):
    name = forms.CharField(label="name", max_length=32)
    desc = forms.CharField(label="desc", max_length=256, required=False)
    path = forms.CharField(label="path", max_length=64)
    sub = forms.CharField(max_length=5, label="sub")
    qos = forms.ChoiceField(choices=Topic.QOS_CHOICES, label="qos")


class NewDataObjectForm(forms.Form):
    name = forms.CharField(label="name", max_length=32)
    desc = forms.CharField(label="desc", max_length=256, required=False)
    data_type = forms.ChoiceField(label="data_type", choices=DataObject.DATA_TYPE_CHOICES)
    path = forms.CharField(label="path", max_length=64, required=False)
    format = forms.ChoiceField(label="format", choices=DataObject.FORMAT_CHOICES)
    key = forms.CharField(label="key", max_length=32, required=False)
    widget_type = forms.ChoiceField(label="widget_type", choices=DataObject.WIDGET_TYPE_CHOICES)

dashboard/views.py
import asyncio
import concurrent.futures
import csv
import logging
import datetime
import time

import django.db.models
import pymongo
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, StreamingHttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
from django.utils.decorators import method_decorator

from guardian.shortcuts import assign_perm, get_perms, get_objects_for_user

from asgiref.sync import async_to_sync, sync_to_async
# from channels.layers import get_channel_layer

from .forms import NewProjectForm, NewTopicForm, NewDataObjectForm
from .models import Project, Topic, DataObject
from .mongodb import get_db_name, db_utils
from .bokeh_utils import BokehPlot
from .mqtt import mqtt_client_manager
from . import utils

from django.views.generic import TemplateView
from django.views import View


# channel_layer = get_channel_layer()
detail_decorators = [login_required(login_url="authentication:login")]


class ViewsMixin:
    required_permissions = None
    user = None
    context = dict()
    template_name = None
    form_class = None

    def set_template_name(self, t_name):
        self.template_name = t_name

    def set_required_permissions(self, permissions_list):
        self.required_permissions = permissions_list

    def set_form_class(self, f_class):
        self.form_class = f_class

    def clear_context(self):
        self.context.clear()

    def add_context_data(self, key, value):
        self.context[str(key)] = value

    def get_topics_for_project(self, project):
        topics = Topic.objects.filter(project=project)
        return topics

    def get_dataobjects_for_topic(self, topic):
        data_objects = DataObject.objects.filter(topic=topic)
        return data_objects

    def get_project(self, project_id):
        try:
            project = Project.objects.get(pk=project_id)
            return project
        except django.db.models.ObjectDoesNotExist:
            return None

    def get_topic(self, topic_id):
        try:
            topic = Topic.objects.get(pk=topic_id)
            return topic
        except django.db.models.ObjectDoesNotExist:
            return None

    def get_data_object(self, dataobject_id):
        try:
            data_object = DataObject.objects.get(pk=dataobject_id)
            return data_object
        except django.db.models.ObjectDoesNotExist:
            return None

    def get_projects(self):
        if not self.user:
            return None
        try:
            projects = get_objects_for_user(self.user, self.required_permissions, any_perm=True)
            return projects
        except django.db.models.ObjectDoesNotExist:
            return None

    def get_projects_param_list(self):
        projects = self.get_projects()
        projects_param_list = list()
        for project in projects:
            topics = self.get_topics_for_project(project)
            mqtt_client = mqtt_client_manager.get_client(project.pk)
            if mqtt_client:
                connected = mqtt_client.connected
            else:
                connected = False

            project_params = {
                "project": project,
                "connected": connected
            }
            projects_entry = {
                "project_params": project_params,
                "topics": topics
            }

            projects_param_list.append(projects_entry)

        return projects_param_list

    def render_template(self, request):
        return render(request, self.template_name, self.context)


@method_decorator(detail_decorators, name="dispatch")
class IndexView(ViewsMixin, TemplateView):
    def __init__(self):
        # super().__init__()
        self.set_template_name("dashboard/index/index.html")
        self.set_required_permissions([
            "dashboard.is_owner",
            "dashboard.can_view",
            "dashboard.can_delete",
        ])

    def get_context_data(self, **kwargs):
        self.clear_context()
        self.context = super().get_context_data(**kwargs)
        self.user = get_user(self.request)
        self.add_context_data("user", self.user)
        self.add_context_data("project_list", self.get_projects_param_list())
        return self.context


@method_decorator(detail_decorators, name="dispatch")
class DetailProjectView(ViewsMixin, TemplateView):
    def __init__(self):
        super().__init__()
        self.set_template_name("dashboard/detail/project.html")

    def get_context_data(self, **kwargs):
        self.clear_context()
        self.context = super().get_context_data()
        project = self.get_project(kwargs["project_id"])
        topics = self.get_topics_for_project(project)
        self.add_context_data("project", project)
        self.add_context_data("topics", topics)
        return self.context


@method_decorator(detail_decorators, name="dispatch")
class DetailTopicView(ViewsMixin, TemplateView):
    def __init__(self):
        super().__init__()
        self.set_template_name("dashboard/detail/topic.html")

    def get_context_data(self, **kwargs):
        self.clear_context()
        self.context = super().get_context_data(**kwargs)
        topic = self.get_topic(kwargs["topic_id"])
        data_objects = self.get_dataobjects_for_topic(topic)
        self.add_context_data("topic", topic)
        self.add_context_data("data_objects", data_objects)
        return self.context


@method_decorator(detail_decorators, name="dispatch")
class DetailDataObjectView(ViewsMixin, TemplateView):
    def __init__(self):
        super().__init__()
        self.set_template_name("dashboard/detail/dataobject.html")

    def get_context_data(self, **kwargs):
        self.clear_context()
        self.context = super().get_context_data(**kwargs)
        data_object = self.get_data_object(kwargs["dataobject_id"])
        topic = self.get_topic(data_object.topic.pk)
        project = self.get_project(topic.project.pk)
        self.add_context_data("dataobject", data_object)
        self.add_context_data("topic", topic)
        self.add_context_data("project", project)
        return self.context


"""
New Views
"""


class NewProjectView(ViewsMixin, View):
    def __init__(self):
        super().__init__()
        self.set_template_name("dashboard/modals/new_project.html")
        self.set_form_class(NewProjectForm)

    def get(self, request, *args, **kwargs):
        initial = {"mqtt_port": 1883}
        self.user = get_user(request)
        if not self.user.is_authenticated:
            return HttpResponse(status=403)

        form = self.form_class(initial=initial)
        self.clear_context()
        self.add_context_data("form", form)
        return self.render_template(request)

    def post(self, request, *args, **kwargs):
        self.user = get_user(request)
        if not self.user.is_authenticated:
            return HttpResponse(status=403)

        self.clear_context()
        form = self.form_class(request.POST)
        if form.is_valid():
            project = Project(
                name=form.cleaned_data["name"],
                description=form.cleaned_data["desc"],
                host=form.cleaned_data["mqtt_host"],
                port=form.cleaned_data["mqtt_port"],
                username=form.cleaned_data["mqtt_username"],
                password=form.cleaned_data["mqtt_password"],
                db_name=get_db_name(self.user),
            )

            try:
                project.save()
            except:
                form.add_error(None, "Unknown error!!")
                self.add_context_data("form", form)
                return self.render_template(request)

            assign_perm("is_owner", self.user, project)
            mqtt_client_manager.add_client(
                client_id=project.pk,
                host=project.host,
                port=project.port,
                userdata=None
            )
            mqtt_client_manager.connect_client(project.pk)
            mqtt_client_manager.start_client(project.pk)
            return HttpResponse(status=201)
        else:
            form.add_error(None, "Form not valid. Please review form and update.")
            self.add_context_data("form", form)
            return self.render_template(request)


class NewTopicView(ViewsMixin, View):
    qos_choices = Topic.QOS_CHOICES

    def __init__(self):
        super().__init__()
        self.set_template_name("dashboard/modals/new_topic.html")
        self.set_form_class(NewTopicForm)

    def subscribe_mqtt_topic(self, project, topic):
        _client = mqtt_client_manager.get_client(project.pk)
        if not _client:
            logging.debug("Not valid client")
            return False

        return async_to_sync(_client.subscribe_topic)(
            topic=topic.path,
            qos=topic.qos
        )

    def get(self, request, *args, **kwargs):
        self.user = get_user(request)
        if not self.user.is_authenticated:
            return HttpResponse(status=403)

        self.clear_context()
        project = self.get_project(kwargs["project_id"])
        initial = {
            "project_id": project.pk,
        }
        form = self.form_class(initial=initial)
        self.add_context_data("form", form)
        self.add_context_data("project", project)
        self.add_context_data("qos_choices", self.qos_choices)
        return self.render_template(request)

    def post(self, request, *args, **kwargs):
        self.user = get_user(request)
        if not self.user.is_authenticated:
            return HttpResponse(status=403)

        self.clear_context()
        project = self.get_project(kwargs["project_id"])
        form = self.form_class(request.POST)
        if form.is_valid():
            topic = Topic(
                name=form.cleaned_data["name"],
                description=form.cleaned_data["desc"],
                path=form.cleaned_data["path"],

templates/dashboard/detail/dataobject.html
{% extends "../base.html" %}
{% load static %}
{% block bokeh_scripts %}
<!-- Bokeh -->
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.0.3.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.0.3.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.0.3.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-3.0.3.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-3.0.3.min.js" crossorigin="anonymous"></script>
{% endblock bokeh_scripts %}
{% block topmenublock %}
{{ topic.name }}
<div class="uk-grid">
    <div class="uk-width-1-1 uk-inline uk-position-z-index" uk-sticky="end:false; offset:80">
        <ul class="uk-breadcrumb">
            <li><a href="{% url 'dashboard:index' %}" class="uk-text-bold">Root</a></li>
            <li><a href="{% url 'dashboard:detail_project' topic.project.id %}" class="uk-text-bold">{{ topic.project.host }}</a></li>
            <li><a href="{% url 'dashboard:detail_topic' topic.id %}" class="uk-text-bold">{{ topic.name }}</a></li>
            <li><a href="{% url 'dashboard:detail_dataobject' dataobject.id %}">{{ dataobject.name }}</a></li>
        </ul>
        <a class="uk-button uk-button-default uk-button-small uk-position-top-right uk-text-secondary" href="{% url 'dashboard:download_csv' dataobject.id %}" target="_blank" rel="noopener noreferrer">
            <span uk-icon="icon: download"></span>
            Download Recent Data
        </a>
    </div>
    <div class="uk-width-1-1">
        <hr>
    </div>
</div>
{% endblock topmenublock %}
{% block maincontentblock %}
<img id="reload-indicator" class="htmx-indicator" src="{% static 'svg-loaders/tail-spin.svg' %}" width="28">
<div id="div-dataobject-data" class="uk-child-width-1-1@s" uk-grid>
    <hr>
    <div id="div-dataobject-swap" hx-get="{% url 'dashboard:get_dataobject_values' dataobject.id %}" hx-trigger="load" hx-swap="outerHTML">
        <div class="uk-container uk-container-expand">
            <img src="{% static 'svg-loaders/tail-spin.svg' %}" width="50"> <span class="uk-container uk-container-expand">Fetching data...</span>
        </div>
    </div>
    <div class="uk-container uk-container-expand" id="div-values-{{ dataobject.id }}">
    </div>
</div>
{% endblock maincontentblock %}
{% block modalsblock %}
{% endblock modalsblock %}

templates/dashboard/detail/project.html
{% extends "../base.html" %}
{% load static %}
{% block topmenublock %}
<div class="uk-card uk-card-body uk-padding-remove uk-background-muted uk-position-z-index" uk-sticky="end: false; offset:84">
    <ul class="uk-breadcrumb">
        <li><a href="{% url 'dashboard:index' %}" class="uk-text-bold">Projects</a></li>
        <li><a href="{% url 'dashboard:detail_project' project.id %}" class="uk-text-bold">{{ project.host }}</a></li>
    </ul>
    <div class="uk-inline uk-position-center-right">
        <img id="new-indicator" class="htmx-indicator" src="{% static 'svg-loaders/tail-spin.svg' %}" width="28">
        <button class="uk-button uk-button-default uk-button-small" hx-get="{% url 'dashboard:new_topic' project.id %}" hx-target="#new-topic-dialog" hx-swap="innerHTML" hx-indicator="#new-indicator">
        <span uk-icon="icon: plus-circle"></span>
        New Topic
        </button>
    </div>
</div>
{% endblock topmenublock %}
{% block maincontentblock %}
<div class="uk-child-width-1-2@s" id="div-main-grid" uk-grid>
    {% include "./include/project_content.html" %}
</div>
{% endblock maincontentblock %}
{% block modalsblock %}
<div id="new-topic-dialog" class="uk-modal uk-modal-container" hx-target="this" esc-close=false bg-close=false>
</div>
{% endblock modalsblock %}
{% block scriptblock %}
{% endblock scriptblock %}

templates/dashboard/detail/topic.html
{% extends "../base.html" %}
{% load static %}
{% block bokeh_scripts %}
      <!-- Bokeh -->
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.0.3.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.0.3.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.0.3.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-3.0.3.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-3.0.3.min.js" crossorigin="anonymous"></script>      
{% endblock bokeh_scripts %}
{% block topmenublock %}
<div class="uk-card uk-card-body uk-padding-remove uk-background-muted uk-position-z-index" uk-sticky="end: false; offset:80">
    <ul class="uk-breadcrumb">
        <li><a href="{% url 'dashboard:index' %}" class="uk-text-bold">Projects</a></li>
        <li><a href="{% url 'dashboard:detail_project' topic.project.id %}" class="uk-text-bold">{{ topic.project.host }}</a></li>
        <li><a href="{% url 'dashboard:detail_topic' topic.id %}" class="uk-text-bold">{{ topic.name }}</a></li>
    </ul>
    <div class="uk-inline uk-position-center-right">
        <img id="new-indicator" class="htmx-indicator" src="{% static 'svg-loaders/tail-spin.svg' %}" width="28">
        <button class="uk-button uk-button-default uk-button-small" hx-get="{% url 'dashboard:new_dataobject' topic.id %}" hx-target="#new-dataobject-dialog" hx-swap="innerHTML" hx-indicator="#new-indicator">
            <span uk-icon="icon: plus-circle"></span>
            New Data Field
        </button>
    </div>
</div>
{% endblock topmenublock %}
{% block maincontentblock %}
<div class="uk-container uk-container-expand uk-overflow-auto uk-height-viewport">
    <div class="uk-child-width-1-2@s" id="div-main-grid" uk-grid>
        {% include "./include/topic_content.html" %}
    </div>
</div>
{% endblock maincontentblock %}
{% block modalsblock %}
<div id="new-dataobject-dialog" class="uk-modal uk-modal-container" hx-target="this" esc-close=false bg-close=false>
</div>
<div id="edit-dataobject-dialog" class="uk-modal uk-modal-container" hx-target="this" esc-close=false bg-close=false>
</div>
{% endblock modalsblock %}