dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"


detail_urls = [
    path("project/<slug:project_id>/", views.DetailProjectView.as_view(), name="detail_project"),
    path("topic/<slug:topic_id>/", views.DetailTopicView.as_view(), name="detail_topic"),
    path("dataobject/<slug:dataobject_id>", views.DetailDataObjectView.as_view(), name="detail_dataobject"),
]

new_urls = [
    path("project/new/", views.NewProjectView.as_view(), name="new_project"),
    path("topic/new/<slug:project_id>/", views.NewTopicView.as_view(), name="new_topic"),
    path("dataobject/new/<slug:topic_id>", views.NewDataObject.as_view(), name="new_dataobject"),
]

delete_urls = [
    path("project/delete/<slug:project_id>/", views.DeleteProjectView.as_view(), name="delete_project"),
    path("topic/delete/<slug:topic_id>/", views.DeleteTopicView.as_view(), name="delete_topic"),
    path("dataobject/delete/<slug:dataobject_id>", views.DeleteDataObject.as_view(), name="delete_dataobject")
]

edit_urls = [
    path("dataobject/edit/<slug:dataobject_id>", views.EditDataObjectView.as_view(), name="edit_dataobject"),
]

ajax_urls = [
    path("htmx_ajax/topic/mongo_dataobject/<slug:topic_id>", views.QueryDataObjectsView.as_view(),
         name="query_dataobjects"),
    path("htmx_ajax/mongo_dataobject/values/<slug:dataobject_id>/", views.QueryDataObjectValues.as_view(),
         name="get_dataobject_values"),
    path("html_ajax/connection/refresh", views.RefreshConnectionsView.as_view(), name="refresh_connections"),
    path("html_ajax/connection/check/<slug:project_id>", views.CheckConnectionView.as_view(), name="check_connection"),
]

download_urls = [
    path("download/dataobject/<slug:dataobject_id>/", views.DownloadView.as_view(), name="download_csv"),
]

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
] + new_urls + delete_urls + detail_urls + ajax_urls + download_urls + edit_urls

ist_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('auth/', include("authentication.urls")),
    path('', include("dashboard.urls")),
]

templates/dashboard/index/include/index_content.html
{% load static %}
{% for project_info in project_list %}
<div id="div-project-{{project_info.project_params.project.id}}" hx-ws="connect:/ws/project/{{project_info.project_params.project.id}}/">
    <div class="uk-card uk-card-default uk-card-hover">
        <div class="uk-card-header">
            <div class="uk-flex-column">
                <span class="uk-card-title">{{ project_info.project_params.project.name }}</span>
                <span class="uk-h6">({{ project_info.project_params.project.host }})</span>
                <div class="uk-flex-row" id="connection-status-div" hx-get="{% url 'dashboard:check_connection' project_info.project_params.project.id %}" hx-trigger="every 2s">
                    {% if project_info.project_params.connected %}
                    <div class="uk-inline" id="connected-indicator">
                        <span class="uk-label uk-label-success">Connected</span>
                    </div>
                    {% else %}
                    <div class="uk-inline" id="disconnected-indicator">
                        <span class="uk-label uk-label-danger">Disconnected</span>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="uk-position-top-right uk-flex-row uk-padding-small">
                <img id="deleting_indicator_{{project_info.project_params.project.id}}" class="htmx-indicator" src="{% static 'svg-loaders/tail-spin.svg' %}" width="28">
                <a href="{% url 'dashboard:detail_project' project_info.project_params.project.id %}" class="uk-button uk-button-small uk-button-default">
                    <span uk-icon="more"></span>
                </a>
                <button class="uk-button uk-button-small uk-button-danger" hx-get="{% url 'dashboard:delete_project' project_info.project_params.project.id %}" hx-target="#div-main-grid" hx-indicator="#deleting_indicator_{{project_info.project_params.project.id}}" hx-confirm="Delete project {{ project_info.project_params.project.name }}?">
                    <span uk-icon="trash"></span>
                </button>
            </div>
        </div>
        <div class="uk-card-body">
            <ul class="uk-list">
                {% for topic in project_info.topics %}
                <li>
                    <div class="uk-grid uk-child-width-1-3">
                        <span>{{ topic.id }}</span>
                        <span>{{ topic.name }}</span>
                    </div>
                </li>
                {% empty %}
                <li>No topics...</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% empty %}
<h3 class="uk-text-muted">No projects..</h3>
{% endfor %}